export const VOCATION_SELECTION = 'VOCATION_SELECTION';
export const VOCATION_STACK = 'VOCATION_STACK';

const DRAG_ITEM_KEYS = {
  VOCATION_SELECTION,
  VOCATION_STACK,
} as const;

export default DRAG_ITEM_KEYS;
